[project]
name = "fantasybaseball"
version = "0.1.0"
description = "Sync fangraphs depth chart projections with a Yahoo fantasy baseball league"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel==6.29.5",
    "loguru==0.7.3",
    "numpy==2.2.4",
    "pandas==2.2.3",
    "pybaseball",
    "requests==2.32.3",
    "yahoo-oauth==2.1.1",
]
